### ISSUE TITLE
Last character not decoded when message is 80 chars with pocsag1200

### ISSUE THREAD

**Issue by christianschneider89** [EliasOenal/multimon-ng#114]
Hello

When a message is 80 characters long, multimon-ng sometimes does not decode/show the last character.
With other decoding tools the message is completly decoded with 80 chars.
Messages shorter than 80 characters are always decoded correctly by multimon-ng (no missing last character).

Chris

**Comment by jdenoy** [comment]
open issue #134 for similar problem. Messages above 80 caracters are truncated

**Comment by christianschneider89** [comment]
In order that #134 was an false alert, this is still open.

**Comment by davide1995** [comment]
Any update on this? With PDW I can see the full message. With multimon-ng sometimes the last character is truncated

**Comment by girst** [comment]
Pinging potentially interested people: I wrote a patch in https://github.com/EliasOenal/multimon-ng/pull/179
