### ISSUE TITLE
Flex Tone-Only messages with short numeric body

### ISSUE THREAD

**Issue by PimHaarsma** [EliasOenal/multimon-ng#120]
Hello,

The tone-only messages of FLEX could have a numeric body. Currently multimon-ng shows these messages only as "TON". On PDW and Pager it has a numeric message.

An example of tone-only, with numeric body: (it should be: 539).
[flex_tone_only_shortnumeric.zip](https://github.com/EliasOenal/multimon-ng/files/2778971/flex_tone_only_shortnumeric.zip)

Sorry, I'm not good in pull requests, so someone else can do that ;-)
The edits i have made, to make it work:

```
*** demod_flex.c	2019-01-24 18:47:43.000000000 +0100
--- demod_flex_edit.c	2019-01-24 18:50:45.000000000 +0100
***************
*** 637,648 ****
  }
  
  
! static void parse_tone_only(struct Flex * flex, char PhaseNo) {
  	if (flex==NULL) return;
  	time_t now=time(NULL);
  	struct tm * gmt=gmtime(&now);
! 	verbprintf(0,  "FLEX: %04i-%02i-%02i %02i:%02i:%02i %i/%i/%c %02i.%03i [%09lld] TON\n", gmt->tm_year+1900, gmt->tm_mon+1, gmt->tm_mday, gmt->tm_hour, gmt->tm_min, gmt->tm_sec,
  			flex->Sync.baud, flex->Sync.levels, PhaseNo, flex->FIW.cycleno, flex->FIW.frameno, flex->Decode.capcode);
  }
  
  
--- 637,675 ----
  }
  
  
! static void parse_tone_only(struct Flex * flex, unsigned int * phaseptr, char PhaseNo, int j) {
  	if (flex==NULL) return;
+ 	unsigned const char flex_bcd[17] = "0123456789 U -][";
+ 	
  	time_t now=time(NULL);
  	struct tm * gmt=gmtime(&now);
! 	verbprintf(0,  "FLEX: %04i-%02i-%02i %02i:%02i:%02i %i/%i/%c %02i.%03i [%09lld] TON ", gmt->tm_year+1900, gmt->tm_mon+1, gmt->tm_mday, gmt->tm_hour, gmt->tm_min, gmt->tm_sec,
  			flex->Sync.baud, flex->Sync.levels, PhaseNo, flex->FIW.cycleno, flex->FIW.frameno, flex->Decode.capcode);
+ 	
+ 	
+ 	// message type
+ 	// 1=tone-only, 0=short numeric
+ 	int w1 = phaseptr[j] >> 7 & 0x03; 
+ 	if(!w1)
+ 	{
+ 		unsigned char digit = 0;
+ 		int i;
+ 		for (i=9; i<=17; i+=4)
+ 		{
+ 			digit = (phaseptr[j] >> i) & 0x0f;
+ 			verbprintf(0, "%c", flex_bcd[digit]);
+ 		}
+ 		
+ 		if (flex->Decode.long_address)
+ 		{
+ 			for (i=0; i<=16; i+=4)
+ 			{
+ 				digit = (phaseptr[j+1] >> i) & 0x0f;
+ 				verbprintf(0, "%c", flex_bcd[digit]);
+ 			}
+ 		}
+ 	}
+ 	verbprintf(0, "\n");
  }
  
  
***************
*** 828,834 ****
  		else if (is_numeric_page(flex))
  			parse_numeric(flex, phaseptr, PhaseNo, j);
  		else if (is_tone_page(flex))
! 			parse_tone_only(flex, PhaseNo);
  		else
  			parse_unknown(flex, phaseptr, PhaseNo, mw1, mw2);
  	}
--- 855,861 ----
  		else if (is_numeric_page(flex))
  			parse_numeric(flex, phaseptr, PhaseNo, j);
  		else if (is_tone_page(flex))
! 			parse_tone_only(flex, phaseptr, PhaseNo, j);
  		else
  			parse_unknown(flex, phaseptr, PhaseNo, mw1, mw2);
  	}
```

**Comment by rob0101** [comment]
Just wrote this as a separate issue, but having seen this I think it's the same issue...


A wipath Paging Data Receiver sees this message:

0400 123 456

which is an Aussie mobile phone number in the local preferred style.

demod_flex.c will present it as

0400123456

and marks the message as 'NUM'. From observation, 99.99% of messages on the SAGRN paging network are tagged as alphanumeric 'ALN', the rest are phone numbers that demod_flex.c tags as 'NUM'.

I haven't delved deep into the code to determine if the pager message was sent as 'NUM' or interpreted as 'NUM' by demod_flex..c. My C skills are very rusty.

The stripping of the spaces in the original message is undesireable. I'd call that a bug.

Don't know if 'NUM' instead of 'ALN' is correct or another bug.

**Comment by rob0101** [comment]
FYI,  "123456" and "1234 56" are both 'FLEX_PAGETYPE_STANDARD_NUMERIC'  when sent over SAGRN.

**Comment by ScanCaster** [comment]
If any one in these threads is using SDR's as their input source with rtl_fm as the input, I would very much appreciate getting input on your settings for rtl_fm and getting output from rtl_fm that multimon will decode Flex reliably.

Please post any input you have at:

https://github.com/EliasOenal/multimon-ng/issues/115

Thanks.

**Comment by rob0101** [comment]
This will fix the missing spaces. There's currently a deliberate check for spaces in the 'number' and they get skipped.

Doing this makes multimon-ng consisted with my Apollo pager and a wipath receiver.

`--- /tmp/demod_flex.c	2019-01-23 14:03:02.000000000 +1030
+++ ../demod_flex.c	2019-01-23 14:01:57.000000000 +1030
@@ -625,9 +625,9 @@
 			}
 			dw >>= 1;
 			if(--count == 0) {
-				if(digit != 0x0C) {// Fill
+//				if(digit != 0x0C) {// Fill
 					verbprintf(0, "%c", flex_bcd[digit]);
-				}
+//				}
 				count = 4;
 			}
 		}
`

**Comment by Zanoroy** [comment]
@PimHaarsma: Can this ticket be closed please?
