### ISSUE TITLE
multimon-ng output help

### ISSUE THREAD

**Issue by ortizjd** [EliasOenal/multimon-ng#128]
Howdy!

I am working on an SDR project on a Raspberry Pi3 B+ and have recently gotten stuck. I am using rtl_fm and a dongle along with multimon-ng to demodulate EAS messages. When multimon-ng outputs directly to stderr and stdout, everything is working perfectly. However, I would like to take the output from multimong-ng and pipe that EAS message into another application. An example multimon-ng output I would like to capture would be:

EAS: ZCZC-WXR-RWT-018139-018109-018059-018159-018065-018011-018057-018035-018145-018095-018063-018097-018031-018081+0600-0441610-KIND/NWS-

However, I cannot seem to capture this output outside of stdout. Any time I try to redirect stdout I get no output at all from multimon-ng. After working through some examples, I discovered anytime I redirect, I no longer see the line "Enabled demodulators: EAS" when mulitmon-ng starts. I have attached a few screenshots to depict this. As you can see, when I run the application normally, I see that line. If I redirect ONLY stderr, I see ONLY that one line in stdout (the rest is written to stderr and thus ends up in the file).

I have tried every solution I can think of, including python subprocesses suggested in a similar thread but nothing works. Has anyone figured out how to get this output from stdout into another program? I am wondering if this is related to the thread about not getting input properly when using tee? There is also the [dsame project](https://github.com/cuppa-joe/dsame) that will decode the EAS string into the readable text and the examples use multimon-ng as an input...but that does not work for me either (since I get no output).

Any thoughts or help on this is much appreciated!

Thank you!
Jason

![redirect_stdout](https://user-images.githubusercontent.com/25017150/52799656-41ba0780-3048-11e9-893e-b5e04859c7c9.png)
![no_redirects](https://user-images.githubusercontent.com/25017150/52799657-42529e00-3048-11e9-9c60-289e5d1baef9.png)
![redirect_stderr](https://user-images.githubusercontent.com/25017150/52799658-42529e00-3048-11e9-96e2-85d17667cae6.png)
![outfile_when_stderr_redirected](https://user-images.githubusercontent.com/25017150/52799659-42529e00-3048-11e9-958c-b5d7614bb022.png)

**Comment by Arnie97** [comment]
I could not reproduce this bug. Would you please paste the contents of the `run_sdr` script?

**Comment by ortizjd** [comment]
Hi there!

Thanks for looking at it! Sure thing...run_sdr is just a one line bash script and it doesn't matter if this is in a script or directly input to the command line, I get the same issue. Here is the command I am trying to use

rtl_fm -f 162.550M -M fm -s 22050 -E dc -g 48 -p 0 -| multimon-ng -a EAS -v 1 -t raw /dev/stdin

I have also tried 

rtl_fm -f 162.550M -M fm -s 22050 -E dc -g 48 -p 0 -| multimon-ng -a EAS -v 1 -t raw -

This has been very puzzling to me...running that command alone will produce the expected output. However, as soon as I try to pipe the output of the above, I observe the issue. In that scenario, rtl_fm and multimon both run just fine, but there are no enabled demodulators (and thus no output).

Thanks again!
Jason

**Comment by posixPilot** [comment]
Jason,

When you redirect the output into a file, the STDOUT file handle becomes buffered by default.  Looking though multimon code, the author normally calls fflush(stdout) to help display the data along in a timely fashion, but there isn't a fflush() call after it prints the "Enabled demodulators" line.  I added the following code on line 839 of unixinput.c to force the fflush() call:

```
    if(!dont_flush)
        fflush(stdout); 
```

This fixes the demodulators output line.  Are you certain that the EAS message line isn't showing up too?

I'm actually working on the same project that you are (i.e. RPi/SDR/multimon-ng/dsame.py) .  I assumed that the EAS message would show up on STDOUT, but I don't have a way to test it without waiting for the weekly scheduled test.  I also don't have a way to know if I need to fflush() that message too, without also waiting for the weekly test.  Have you found a way to feed a EAS recording into multimon-ng for testing?  The only EAS recording I could find doesn't seem to decode; I'm using sox to convert it to a raw format.

  Thanks
  Mike

**Comment by ortizjd** [comment]
Hi Mike,

Nice find! Adding fflush there at least shows me the setup is correct. I also have to wait for the weekly tests on Wednesday....Essentially, when I am running multimon on its own, the encoded message prints to STDOUT and I can then copy and past that into a file and read it with dsame to see the message. However, when piping directly into dsame, I do not see the message printed to STDOUT. For this week's test, I have modified the dsame code to post the data to an API...I guess this will tell me if the message is being processed and just not flushed from the STDOUT buffer.

I will keep this thread updated if that works!

Thank you,
Jason

**Comment by posixPilot** [comment]
Hi Jason,

You might be having the same issue with dsame (buffering).  I only know about this issue because I bump into it frequently when I script in Perl.  Perl allows you to select a file handle and disable buffering; I would guess that Python/dsame have a similar attribute.

For my implementation, I'm having Perl monitor the output from multimon-ng.  If I see a line prefixed with "EAS: ", then I split out the encoded NWS message, and pass that to dsame.py with the --msg flag.  It is working pretty well.

Also, while I was poking around in the dsame directory, I found a recorded EAS message (under sample\ alert/WXR-RWT.ogg ).  Using sox, you can feed this into multimon-ng to test your setup.  This is how I call the sample from my Perl script:

`/usr/bin/sox /usr/src/dsame/sample\ alert/WXR-RWT.ogg -esigned-integer -b16 -r 22050 -t raw - 2> /dev/null | /usr/local/bin/multimon-ng -t raw
 -a EAS - 2> /dev/null`

  Cheers
  Mike

**Comment by ortizjd** [comment]
Hi Mike!

Great news! I do believe the issue was related to STDOUT buffering as I received the test message today and successfully called my API. I am going to continue testing with the ogg sample as you suggested but I feel like this issue is resolved! Thank you for the help and ideas!

Jason
