### ISSUE TITLE
Missing last character when page length is a multiple of 40

### ISSUE THREAD

**Issue by panserbjorne** [EliasOenal/multimon-ng#140]
Hey,

Not sure if I'm doing something wrong. I'm decoding POCSAG512, and I've noticed that if the length of a page is a multiple of 40, it drops the last character. I can see the full message in another decoding program, PDW.

I've attached a wav file recorded in audacity via SDR#.
[example.zip](https://github.com/EliasOenal/multimon-ng/files/3877479/example.zip)

The original message that was sent:
This is a test message, 80 chars. The last character, 'z' will be missing. vwxyz

The command I ran:
sox -t wav example.wav -esigned-integer -b16 -r 22050 -t raw - | multimon-ng -q -f auto -a POCSAG512 -

The output:
POCSAG512: Address: 1515502  Function: 0  Alpha:   This is a test message, 80 chars. The last character, 'z' will be missing. vwxy

**Comment by EliasOenal** [comment]
See #134 and #114.

**Comment by girst** [comment]
Pinging potentially interested people: I wrote a patch in https://github.com/EliasOenal/multimon-ng/pull/179
