### ISSUE TITLE
Error after qmake ../multimon-ng.pro

### ISSUE THREAD

**Issue by tomswinkels** [EliasOenal/multimon-ng#145]
Something wrong?

![image](https://user-images.githubusercontent.com/9036151/74062155-e79b1a80-49ed-11ea-8bb4-605bbd64c3f6.png)

**Comment by snailcatcher** [comment]
I got the same issue.

**Comment by EliasOenal** [comment]
Those are just warnings and should still allow the build to complete. Did it result in a binary?

**Comment by snailcatcher** [comment]
> Those are just warnings and should still allow the build to complete. Did it result in a binary?

I think so. I build multimon-ng inside a docker container (using raspbian buster) and after building i can run my container as expected.
But i'm not sure if multimon-ng ist working correctly and if the data it provides is correct.

**Comment by EliasOenal** [comment]
Feel free to report any bugs you encounter, though I would assume it to work fine.
