### ISSUE TITLE
-a SCOPE doesn't work

### ISSUE THREAD

**Issue by christianschneider89** [EliasOenal/multimon-ng#151]
Hello

When I use "-a SCOPE" I get:

invalid mode "SCOPE"
multimon-ng 1.1.8

Chris

**Comment by EliasOenal** [comment]
Was the feature enabled during compilation?

**Comment by ScanCaster** [comment]
I get this, so what are the CORRECT 

1) dependencies to build this??? Debian/*buntus 18.04, 20.04?

2) Correct option for cmake? I tried - X11 and about 30 other variants on this with X11 and didn't trigger it to try to make with that option and/or fail that it needed some libs to do so ????

**Comment by EliasOenal** [comment]
Cmake should detect it once the dependencies have been met. The Debian packages should be _libx11_, as well as the development package _libx11-dev_. https://packages.debian.org/search?keywords=libx11
