### ISSUE TITLE
Using message time instead of system received time 

### ISSUE THREAD

**Issue by SimonRijn** [EliasOenal/multimon-ng#164]
Whilst looking through the code, I've noticed that the 'receiving time' is being generated by the system time, instead of using the time that's included in the signal.

This would mean that when using two different systems, both times would be different.

Is this correct, or am I missing something?

Thanks in advance!

**Comment by rfarley3** [comment]
PDW/Flex.cpp has code to demod the network time. Apart from more accurate output (esp for recordings), I think it'd be a pretty cool time source. I spent a few hours in any specs and docs I could find. All I found was references but no methods to decode.  So it's possible.
