### ISSUE TITLE
Problems with decoding EU letters

### ISSUE THREAD

**Issue by Hayvosh** [EliasOenal/multimon-ng#174]
When using multimon-ng together with rtl_sdr on a RPi to decode pocsag here in Sweden for example, it has some issues with decoding the letter Å  as seen in the example below.
And when using my physical pocsag pager it works just fine, just multimon-ng that seems to interpret the messages wrong.

This is the line I use 
rtl_fm -f 149.3875M -l 50 -g 37 -s 22050 - | multimon-ng -t raw -a POCSAG2400 -a POCSAG1200 -a POCSAG512 -f alpha /dev/stdin

Which gives me this : 
20:41:27 POCSAG1200: Address:  408888  Function: 0  Alpha:  Omfattning: Lüg Övrigt I lekparken i närheten av poolen 14 üring fast i en gunga.  Q1000<NUL><NUL>

In this example the letter "ü" should be "å"

**Comment by Hayvosh** [comment]
Found a fix to modify pocsag.c file and alter the following lines with this :

`{ 0x5d, ”Å” }, /* upper case U dieresis */`
`{ 0x7d, ”å” }, /* lower case u dieresis */`

But maybe find a way to change regional settings in a config file

**Comment by weinholt** [comment]
Try `-C SE` on the command line, that should make it decode with the Swedish charset.

**Comment by weinholt** [comment]
Du bör också veta att du har tystnadsplikt för meddelanden som du tar emot på det här sättet, enligt 6 kap. 23 § lag om elektronisk kommunikation
