### ISSUE TITLE
GQRX output not decoding on rpi

### ISSUE THREAD

**Issue by icissel** [EliasOenal/multimon-ng#182]
I am trying to pipe sdr stream from gqrx to multimon-ng with the following:
`nc -l -u localhost 7355 |
    sox -t raw -esigned-integer -b 16 -r 48000 - -esigned-integer -b 16 -r 22050 -t raw - |
    multimon-ng -t raw -a POCSAG512 -a POCSAG1200 -a POCSAG2400 -a FLEX  -f alpha -`

the gqrx settings are set as shown below

running that script shows:
`multimon-ng 1.1.9
  (C) 1996/1997 by Tom Sailer HB9JNX/AE4WA
  (C) 2012-2020 by Elias Oenal
Available demodulators: POCSAG512 POCSAG1200 POCSAG2400 FLEX EAS UFSK1200 CLIPFSK FMSFSK AFSK1200 AFSK2400 AFSK2400_2 AFSK2400_3 HAPN4800 FSK9600 DTMF ZVEI1 ZVEI2 ZVEI3 DZVEI PZVEI EEA EIA CCIR MORSE_CW DUMPCSV X10 SCOPE
Enabled demodulators: POCSAG512 POCSAG1200 POCSAG2400 FLEX`

I get plenty of output when i run `nc -l -u localhost 7355`.  Also, decoding works as espected when I pipe rtl_fm to multimon with the same sox parameters as above

![image](https://user-images.githubusercontent.com/32376179/151674807-4fe51a6b-c2c9-412c-b4b6-469cdbf8680b.png)

**Comment by weinholt** [comment]
I don't have any problem decoding gqrx output on a Raspberry Pi. Could it be because you've checked the "stereo" checkbox? SoX is probably expecting mono data.

**Comment by icissel** [comment]
thanks for mentioning that...I clicked stereo on during my last troubleshoot prior to posting but even in mono it still doesnt decode

**Comment by icissel** [comment]
interestingly, when i run the multimon-ng script while connected to the pi via vnc viewer with a terminal shell open i get no output.  However, when i open and tune gqrx via vnc viewer and then run the multimon script in an ssh shell it works fine.

**Comment by leecollingsco** [comment]
Hi everyone, I need to ask because I'm having real trouble trying to decode POGSAC on RPi4 (on every tutorial I find).

This one is the most helpful, however when I try and run nc commands (nc -l -u localhost 7355), this doesn't look to be installed on my Pi.

```
lee@raspberrypi:~/multimon-ng/build $ nc -l -u localhost 7355
bash: nc: command not found
```

Do I just need to install nc? This wasn't mentioned anywhere in the installation instructions...
