### ISSUE TITLE
Version 1.2.0 not tagged

### ISSUE THREAD

**Issue by girst** [EliasOenal/multimon-ng#199]
Just found out that you released version 1.2.0 a few months ago. Because it is not tagged and no github release created, it didn't notify release-watchers like me.

It'll be great if you could please tag the release, the relevant commit seems to be b0c4ea451033219ef81acd2f59778317cfc17064.

**Comment by EliasOenal** [comment]
I hadn't tagged it yet, since I intended to wait for feedback regarding the major changes to the FLEX decoder. But I'll tag it now. Thanks!
