### ISSUE TITLE
Can there be better installation instructions?

### ISSUE THREAD

**Issue by leecollings** [EliasOenal/multimon-ng#208]
Hello,

I've come here after failing to be able to install pagermon (because of terminal errors and that package installation steps not exactly being helpful), and I've found these installation steps are equally not as helpful.

Can you adapt them to make it clear how to get this up and running from a new system install? For example, you referencing using qmake or cmake (but then give no instruction on how to install these)...

When I run a qmake command, I get the following:

```
qmake: could not exec '/usr/lib/qt5/bin/qmake': No such file or directory
```

So some better installation instructions would be really helpful. So far, using a Raspberry Pi 4, it seems absolutely impossible to be able to decode POGSAC messages on this (as every online tutorial or project I've tried simply doesn't work, with little installation support).

Any help is greatly appreciated.

**Comment by leecollingsco** [comment]
Eventually I managed to install cmake, and then ran through the installation instructions, but there are errors and warnings coming back after installing:

```
lee@raspberrypi:~/multimon-ng/build $ sudo make install
Scanning dependencies of target multimon-ng
[  2%] Building C object CMakeFiles/multimon-ng.dir/BCHCode.c.o
[  5%] Building C object CMakeFiles/multimon-ng.dir/unixinput.c.o
[  7%] Building C object CMakeFiles/multimon-ng.dir/uart.c.o
[ 10%] Building C object CMakeFiles/multimon-ng.dir/pocsag.c.o
[ 13%] Building C object CMakeFiles/multimon-ng.dir/selcall.c.o
[ 15%] Building C object CMakeFiles/multimon-ng.dir/hdlc.c.o
[ 18%] Building C object CMakeFiles/multimon-ng.dir/demod_zvei1.c.o
[ 21%] Building C object CMakeFiles/multimon-ng.dir/demod_zvei2.c.o
[ 23%] Building C object CMakeFiles/multimon-ng.dir/demod_zvei3.c.o
[ 26%] Building C object CMakeFiles/multimon-ng.dir/demod_pzvei.c.o
[ 28%] Building C object CMakeFiles/multimon-ng.dir/demod_dzvei.c.o
[ 31%] Building C object CMakeFiles/multimon-ng.dir/demod_ccir.c.o
[ 34%] Building C object CMakeFiles/multimon-ng.dir/demod_eia.c.o
[ 36%] Building C object CMakeFiles/multimon-ng.dir/demod_eea.c.o
[ 39%] Building C object CMakeFiles/multimon-ng.dir/demod_ufsk12.c.o
[ 42%] Building C object CMakeFiles/multimon-ng.dir/demod_poc24.c.o
[ 44%] Building C object CMakeFiles/multimon-ng.dir/demod_poc12.c.o
[ 47%] Building C object CMakeFiles/multimon-ng.dir/demod_poc5.c.o
[ 50%] Building C object CMakeFiles/multimon-ng.dir/demod_hapn48.c.o
[ 52%] Building C object CMakeFiles/multimon-ng.dir/demod_fsk96.c.o
[ 55%] Building C object CMakeFiles/multimon-ng.dir/demod_dtmf.c.o
[ 57%] Building C object CMakeFiles/multimon-ng.dir/demod_clipfsk.c.o
[ 60%] Building C object CMakeFiles/multimon-ng.dir/demod_fmsfsk.c.o
[ 63%] Building C object CMakeFiles/multimon-ng.dir/demod_afsk24.c.o
[ 65%] Building C object CMakeFiles/multimon-ng.dir/demod_afsk24_3.c.o
[ 68%] Building C object CMakeFiles/multimon-ng.dir/demod_afsk24_2.c.o
[ 71%] Building C object CMakeFiles/multimon-ng.dir/demod_afsk12.c.o
[ 73%] Building C object CMakeFiles/multimon-ng.dir/demod_flex.c.o
/home/lee/multimon-ng/demod_flex.c: In function ‘parse_alphanumeric’:
/home/lee/multimon-ng/demod_flex.c:593:104: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 15 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
  593 | t pt_offset = sprintf(pt_out, "FLEX|%04i-%02i-%02i %02i:%02i:%02i|%i/%i/%c/%c|%02i.%03i|%09lld",
      |                                                                                         ~~~~~^
      |                                                                                              |
      |                                                                                              long long int
      |                                                                                         %09ld
  594 |               gmt->tm_year+1900, gmt->tm_mon+1, gmt->tm_mday, gmt->tm_hour, gmt->tm_min, gmt->tm_sec,

  595 |               flex->Sync.baud, flex->Sync.levels, frag_flag, PhaseNo, flex->FIW.cycleno, flex->FIW.frameno, flex->Decode.capcode);
      |                                                                                                             ~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                         |
      |                                                                                                                         int64_t {aka long int}

/home/lee/multimon-ng/demod_flex.c:605:73: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
  605 |                         pt_offset += sprintf(pt_out + pt_offset, " %09lld", flex->GroupHandler.GroupCodes[groupbit][g]);
      |                                                                    ~~~~~^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                         |                                          |
      |                                                                         long long int                              int64_t {aka long int}
      |                                                                    %09ld
[ 76%] Building C object CMakeFiles/multimon-ng.dir/demod_flex_next.c.o
In file included from /home/lee/multimon-ng/demod_flex_next.c:102:
/home/lee/multimon-ng/demod_flex_next.c: In function ‘parse_alphanumeric’:
/home/lee/multimon-ng/demod_flex_next.c:634:19: warning: pointer targets in passing argument 2 of ‘_verbprintf’ differ in signedness [-Wpointer-sign]
  634 |     verbprintf(0, message);
      |                   ^~~~~~~
      |                   |
      |                   unsigned char *
/home/lee/multimon-ng/multimon.h:345:61: note: in definition of macro ‘verbprintf’
  345 |     do { if (level <= MAX_VERBOSE_LEVEL) _verbprintf(level, __VA_ARGS__); } while (0)
      |                                                             ^~~~~~~~~~~
/home/lee/multimon-ng/multimon.h:340:46: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
  340 | void _verbprintf(int verb_level, const char *fmt, ...);
      |                                  ~~~~~~~~~~~~^~~
[ 78%] Building C object CMakeFiles/multimon-ng.dir/costabi.c.o
[ 81%] Building C object CMakeFiles/multimon-ng.dir/costabf.c.o
[ 84%] Building C object CMakeFiles/multimon-ng.dir/clip.c.o
[ 86%] Building C object CMakeFiles/multimon-ng.dir/fms.c.o
[ 89%] Building C object CMakeFiles/multimon-ng.dir/demod_eas.c.o
/home/lee/multimon-ng/demod_eas.c:83:1: warning: variably modified ‘eascorr_mark_i’ at file scope
   83 | static float eascorr_mark_i[CORRLEN];
      | ^~~~~~
/home/lee/multimon-ng/demod_eas.c:84:1: warning: variably modified ‘eascorr_mark_q’ at file scope
   84 | static float eascorr_mark_q[CORRLEN];
      | ^~~~~~
/home/lee/multimon-ng/demod_eas.c:85:1: warning: variably modified ‘eascorr_space_i’ at file scope
   85 | static float eascorr_space_i[CORRLEN];
      | ^~~~~~
/home/lee/multimon-ng/demod_eas.c:86:1: warning: variably modified ‘eascorr_space_q’ at file scope
   86 | static float eascorr_space_q[CORRLEN];
      | ^~~~~~
[ 92%] Building C object CMakeFiles/multimon-ng.dir/demod_morse.c.o
[ 94%] Building C object CMakeFiles/multimon-ng.dir/demod_dumpcsv.c.o
[ 97%] Building C object CMakeFiles/multimon-ng.dir/demod_x10.c.o
[100%] Linking C executable multimon-ng
[100%] Built target multimon-ng
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/share/man/man1/multimon-ng.1
-- Installing: /usr/local/bin/multimon-ng
```

Now it seems installation has completed, but now what? The installation instructions stop here, and there's nothing else I can see in the readme that explains how to actually use this.

Is there a GUI I need to open? I'm using GQRX to scan and listen to frequencies, but how I can then process that into multimon-ng to be able to decode POGSAC messages?

Can you please update your readme to make this much clearer? Thank you!

**Comment by canuckcam** [comment]
I actually just came to write the error too! I'm running Ubuntu 22.04.3 LTS Desktop.

1. Install PulseAudio and x11 dev dependencies
`$ sudo apt install libpulse-dev libx11-dev`

2. Download and compile multimon-ng in ~.
```
$ mkdir multimon-ng
$ git clone https://github.com/EliasOenal/multimon-ng.git
$ cd trunk-build
$ cmake ../multimon-ng
$ make
$ sudo make install
```

Following this, this is my console output:
radio@radio:~/multimon-ng$ make
[  2%] Building C object CMakeFiles/multimon-ng.dir/xdisplay.c.o
[  5%] Building C object CMakeFiles/multimon-ng.dir/demod_display.c.o
[  7%] Building C object CMakeFiles/multimon-ng.dir/BCHCode.c.o
[ 10%] Building C object CMakeFiles/multimon-ng.dir/unixinput.c.o
[ 12%] Building C object CMakeFiles/multimon-ng.dir/uart.c.o
[ 15%] Building C object CMakeFiles/multimon-ng.dir/pocsag.c.o
[ 17%] Building C object CMakeFiles/multimon-ng.dir/selcall.c.o
[ 20%] Building C object CMakeFiles/multimon-ng.dir/hdlc.c.o
[ 22%] Building C object CMakeFiles/multimon-ng.dir/demod_zvei1.c.o
[ 25%] Building C object CMakeFiles/multimon-ng.dir/demod_zvei2.c.o
[ 27%] Building C object CMakeFiles/multimon-ng.dir/demod_zvei3.c.o
[ 30%] Building C object CMakeFiles/multimon-ng.dir/demod_pzvei.c.o
[ 32%] Building C object CMakeFiles/multimon-ng.dir/demod_dzvei.c.o
[ 35%] Building C object CMakeFiles/multimon-ng.dir/demod_ccir.c.o
[ 37%] Building C object CMakeFiles/multimon-ng.dir/demod_eia.c.o
[ 40%] Building C object CMakeFiles/multimon-ng.dir/demod_eea.c.o
[ 42%] Building C object CMakeFiles/multimon-ng.dir/demod_ufsk12.c.o
[ 45%] Building C object CMakeFiles/multimon-ng.dir/demod_poc24.c.o
[ 47%] Building C object CMakeFiles/multimon-ng.dir/demod_poc12.c.o
[ 50%] Building C object CMakeFiles/multimon-ng.dir/demod_poc5.c.o
[ 52%] Building C object CMakeFiles/multimon-ng.dir/demod_hapn48.c.o
[ 55%] Building C object CMakeFiles/multimon-ng.dir/demod_fsk96.c.o
[ 57%] Building C object CMakeFiles/multimon-ng.dir/demod_dtmf.c.o
[ 60%] Building C object CMakeFiles/multimon-ng.dir/demod_clipfsk.c.o
[ 62%] Building C object CMakeFiles/multimon-ng.dir/demod_fmsfsk.c.o
[ 65%] Building C object CMakeFiles/multimon-ng.dir/demod_afsk24.c.o
[ 67%] Building C object CMakeFiles/multimon-ng.dir/demod_afsk24_3.c.o
[ 70%] Building C object CMakeFiles/multimon-ng.dir/demod_afsk24_2.c.o
[ 72%] Building C object CMakeFiles/multimon-ng.dir/demod_afsk12.c.o
[ 75%] Building C object CMakeFiles/multimon-ng.dir/demod_flex.c.o
/home/radio/multimon-ng/demod_flex.c: In function ‘parse_alphanumeric’:
/home/radio/multimon-ng/demod_flex.c:593:104: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 15 has type ‘int64_t’ {aka ‘long in’} [-Wformat=]
  593 | out, "FLEX|%04i-%02i-%02i %02i:%02i:%02i|%i/%i/%c/%c|%02i.%03i|%09lld",
      |                                                                ~~~~~^
      |                                                                     |
      |                                                                     long long int
      |                                                                %09ld
  594 | r+1900, gmt->tm_mon+1, gmt->tm_mday, gmt->tm_hour, gmt->tm_min, gmt->tm_sec,

  595 | baud, flex->Sync.levels, frag_flag, PhaseNo, flex->FIW.cycleno, flex->FIW.frameno, flex->Decode.capcode);
      |                                                                                    ~~~~~~~~~~~~~~~~~~~~
      |                                                                                                |
      |                                                                                                int64_t {aka long int}

/home/radio/multimon-ng/demod_flex.c:605:73: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
  605 |             pt_offset += sprintf(pt_out + pt_offset, " %09lld", flex->GroupHandler.GroupCodes[groupbit][g]);
      |                                                        ~~~~~^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                             |                                          |
      |                                                             long long int                              int64_t {aka long int}
      |                                                        %09ld
[ 77%] Building C object CMakeFiles/multimon-ng.dir/demod_flex_next.c.o
In file included from /home/radio/multimon-ng/demod_flex_next.c:102:
/home/radio/multimon-ng/demod_flex_next.c: In function ‘parse_alphanumeric’:
/home/radio/multimon-ng/demod_flex_next.c:634:19: warning: pointer targets in passing argument 2 of ‘_verbprintf’ differ in signedness [-Wpointer-sign]
  634 |     verbprintf(0, message);
      |                   ^~~~~~~
      |                   |
      |                   unsigned char *
/home/radio/multimon-ng/multimon.h:345:61: note: in definition of macro ‘verbprintf’
  345 |     do { if (level <= MAX_VERBOSE_LEVEL) _verbprintf(level, __VA_ARGS__); } while (0)
      |                                                             ^~~~~~~~~~~
/home/radio/multimon-ng/multimon.h:340:46: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
  340 | void _verbprintf(int verb_level, const char *fmt, ...);
      |                                  ~~~~~~~~~~~~^~~
[ 80%] Building C object CMakeFiles/multimon-ng.dir/costabi.c.o
[ 82%] Building C object CMakeFiles/multimon-ng.dir/costabf.c.o
[ 85%] Building C object CMakeFiles/multimon-ng.dir/clip.c.o
[ 87%] Building C object CMakeFiles/multimon-ng.dir/fms.c.o
[ 90%] Building C object CMakeFiles/multimon-ng.dir/demod_eas.c.o
/home/radio/multimon-ng/demod_eas.c:83:1: warning: variably modified ‘eascorr_mark_i’ at file scope
   83 | static float eascorr_mark_i[CORRLEN];
      | ^~~~~~
/home/radio/multimon-ng/demod_eas.c:84:1: warning: variably modified ‘eascorr_mark_q’ at file scope
   84 | static float eascorr_mark_q[CORRLEN];
      | ^~~~~~
/home/radio/multimon-ng/demod_eas.c:85:1: warning: variably modified ‘eascorr_space_i’ at file scope
   85 | static float eascorr_space_i[CORRLEN];
      | ^~~~~~
/home/radio/multimon-ng/demod_eas.c:86:1: warning: variably modified ‘eascorr_space_q’ at file scope
   86 | static float eascorr_space_q[CORRLEN];
      | ^~~~~~
[ 92%] Building C object CMakeFiles/multimon-ng.dir/demod_morse.c.o
[ 95%] Building C object CMakeFiles/multimon-ng.dir/demod_dumpcsv.c.o
[ 97%] Building C object CMakeFiles/multimon-ng.dir/demod_x10.c.o
[100%] Linking C executable multimon-ng
[100%] Built target multimon-ng

radio@radio:~/multimon-ng$ sudo make install
Consolidate compiler generated dependencies of target multimon-ng
[100%] Built target multimon-ng
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/share/man/man1/multimon-ng.1
-- Installing: /usr/local/bin/multimon-ng
radio@radio-peel-pager:~/multimon-ng$ 
radio@radio-peel-pager:~/multimon-ng$ ./multimon-ng
multimon-ng 1.2.0
  (C) 1996/1997 by Tom Sailer HB9JNX/AE4WA
  (C) 2012-2022 by Elias Oenal
Available demodulators: POCSAG512 POCSAG1200 POCSAG2400 FLEX FLEX_NEXT EAS UFSK1200 CLIPFSK FMSFSK AFSK1200 AFSK2400 AFSK2400_2 AFSK2400_3 HAPN4800 FSK9600 DTMF ZVEI1 ZVEI2 ZVEI3 DZVEI PZVEI EEA EIA CCIR MORSE_CW DUMPCSV X10 SCOPE
Enabled demodulators: POCSAG512 POCSAG1200 POCSAG2400 FLEX FLEX_NEXT EAS UFSK1200 CLIPFSK FMSFSK AFSK1200 AFSK2400 AFSK2400_2 AFSK2400_3 HAPN4800 FSK9600 DTMF ZVEI1 ZVEI2 ZVEI3 DZVEI PZVEI EEA EIA CCIR MORSE_CW DUMPCSV X10 SCOPE
X: Unable to open X display
Enabled demodulators: POCSAG512 POCSAG1200 POCSAG2400 FLEX FLEX_NEXT EAS UFSK1200 CLIPFSK FMSFSK AFSK1200 AFSK2400 AFSK2400_2 AFSK2400_3 HAPN4800 FSK9600 DTMF ZVEI1 ZVEI2 ZVEI3 DZVEI PZVEI EEA EIA CCIR MORSE_CW DUMPCSV X10 SCOPEchild process 12762 died, status 256
0.000000,0
0.045351,0
0.090703,0
0.136054,0
0.181406,0
0.226757,0
0.272109,0
0.317460,0
0.362812,0
0.408163,0
0.453515,0
0.498866,0
0.544218,0
... (continues)

**Comment by AlienResidents** [comment]
Hi,

While it would be nice to have more information in the README, there are a few things that I could recommend for you.

I don't know what level of knowledge you have running Linux, and the first thing I would recommend is to run the command "man man", without quotes. Read through that manual (man) page, and then when you are comfortable with that information, move on to the next paragraph.

With the knowledge of what man is, and how to use it, and the output you pasted from the installation commands (it's a good idea to read through all of that), the last 2 lines in the output you pasted are telling you exactly what was installed, and where it was installed.  The penultimate line is telling you that a man page was installed at "/usr/local/share/man/man1/multimon-ng.1".  Using man you could read how to use what you have installed by typing "man multimon-ng", and hitting enter, and reading through that man page.
