### ISSUE TITLE
POCSAG decoder fails unless fed data in large chunks

### ISSUE THREAD

**Issue by luarvique** [EliasOenal/multimon-ng#213]
When running multimon-ng 1.1.9 executable and feeding it IQ input via a pipe, POCSAG decoders spew garbage unless the data is written in chunks of at least 512 complete IQ samples at a time. The FLEX decoder appears to be unaffected though.

The problem was found when running a background POCSAG/FLEX decoder in OpenWebRX+ as opposed to running it interactively. In the interactive mode, OpenWebRX+ has a Squelch() module in its DSP chain that buffers data in 1024-sample chunks. In the background mode, where Squelch() is not present and data arrives in smaller increments, POCSAG breaks.

I can obviously implement buffering at the input to multimon-ng, but it probably better be addressed in the multimon-ng code as well.

**Comment by EliasOenal** [comment]
Thanks for the report, I'd be happy to accept a PR for this issue.

**Comment by luarvique** [comment]
I have not got to the point of finding the exact culprit inside multimon-ng. Will try looking at it this upcoming week, but if you know where it may be, don't wait for me =)

**Comment by EliasOenal** [comment]
This issue is related to: #197 #91 #70

**Comment by luarvique** [comment]
Fixed with pull request #214. Came down to incorrect subsample tracking between separate portions of incoming data. The same issue might be present in some other decoders, I have not checked.

**Comment by luarvique** [comment]
I am seeing the same subsampling issue in demod_fmsfsk.c. You may want to check the rest.

**Comment by luarvique** [comment]
> Thanks for the report, I'd be happy to accept a PR for this issue.

The PR is waiting for your review and approval. I will wait fixing remaining decoders (such as FMSFSK) until the current PR is merged in.

**Comment by luarvique** [comment]
PR got merged, so closing this one. Will make similar fixes to other decoders that use the same subsampling method.
