### ISSUE TITLE
Making a new multimon-ng release

### ISSUE THREAD

**Issue by luarvique** [EliasOenal/multimon-ng#216]
Sorry to bother you about this, but is there any way to trigger multimon-ng package updates in various Linux repositories? Maybe create a new multimon-ng release?

The reason is that most of OpenWebRX+ users install multimon-ng with apt, so they do not get the recently merged subsampling fix, so I have to keep the workaround hack in OpenWebRX+ until those repositories are updated with the new version.

**Comment by EliasOenal** [comment]
I like to wait a few weeks before releases, in case of regressions that went unnoticed. But I'll release a new version soon. From there the maintainers will update their respective packages.

**Comment by luarvique** [comment]
Understood and thanks!
