### ISSUE TITLE
Strange message format

### ISSUE THREAD

**Issue by Murf** [EliasOenal/multimon-ng#30]
Hi,
I see quite a few messages of this format:
POCSAG512: Address:    3200  Function: 0  Alpha:   )&)E51ASNPPEB8491098000100008000&Q0200&Q0201&Q0202&Q0203&Q0204&Q0205&Q0206&Q0207&Q0208&Q0209&Q02
0:&Q020;&Q020<&Q020=&Q020>&Q020?&Q0210&Q0211&Q0212&Q0213&Q0214&P16000019?::8103000000001&P160100088;=8103000000001&P160200088;80103000000001&P160300088;?0103
000000001&P160400088<50103000000001&&36<NUL><NUL>

I am using the following multimon-ng paramaters:
multimon-ng -t raw -a POCSAG512 -f alpha /dev/stdin 

The interesting thing is a particular alpha page I was expecting to see at the time did not get decoded.

Any ideas?

**Comment by Murf** [comment]
P.S. it is always to address 3200

**Comment by Murf** [comment]
P.P.S: Thought... OTA reset or update?

**Comment by EliasOenal** [comment]
Interesting, it definitively looks like some form of encoded data. Searching Google for some of those substrings I get similarly encoded data on Japanese sites. For example:
> Q001=0.0&Q002=0.0&Q003=0.0&Q004=0.0&Q005=0.0&Q006=0.0&Q007=0.0&Q008=0.0 (...)

http://un-no-un.net/SEA/setX/Q17R.txt

**Comment by Murf** [comment]
The more I look at it the more I am convinced it is an over the air reset requested by pager end users
