### ISSUE TITLE
Windows Parameters

### ISSUE THREAD

**Issue by SEKCobra** [EliasOenal/multimon-ng#32]
Hey, after people recommended I try this cause PDW isn't decoding a fairly strong signal, I am now unable to figure out how to set the input to a certain audio device. The -? information is quite lacking and I couldn't find anymore documentation sadly.

**Comment by EliasOenal** [comment]
So far multimon-ng doesn't support manually selecting audio devices, it always uses the one set as default. Though some people also have reported success using "virtual audio cables".
