### ISSUE TITLE
Not showing anything

### ISSUE THREAD

**Issue by afxmedia** [EliasOenal/multimon-ng#38]
Hi, I just installed multimon-ng on my mac and it doesn't seem to be working. I'm wondering if I've set up anything wrong?

I've run Win7 in VM with SDR# + PDW with a known pager frequency, it was working pretty well and I think it’s FLEX(since it's showing FLEX all the time in the PDW window), but I’m looking for a native mac solution.
so I downloaded & set up sox, gqrx with macports and compiled multimon-ng following the README using qmake(tried both qt5 & qt4).

I setup the GQRX to stream on 7355 UDP port, played some FM radio and used sox to record to wav file, so that part i know is working for sure, but when I turn to the pager frequency and ran the following command, nothing shows up yet I can see the pager signals being transmitted clearly in GQRX.

Here is the command I put in, did I type anything wrong? 

```
nc -l -u 7355 | sox -t raw -e signed-integer -b 16 -c 1 -r 48000 - -e signed-integer -b 16 -r 22050 -t raw - |  multimon-ng -t raw -a FLEX -a POCSAG512 -a POCSAG1200 -a POCSAG2400 -f alpha -
```

I've also tried the without including any of the POCSAG demodulator.

thanks

**Comment by f4t** [comment]
why not using rtl_fm directly rather than gqrx over netcat ?

**Comment by griffinbai** [comment]
You don't need Gqrx .

change the freq and output port below you need . I used to pipe em to Xastir .

rtl_fm -p 18 -f 144940000 -s 22050 - -|multimon-ng -a AFSK1200 -A -t raw - | sed -u -r 's/^.{6}//' | socat STDIN TCP-LISTEN:14580,reuseaddr,fork

**Comment by afxmedia** [comment]
@f4t tried rtl_fm, doesn't work either. Also because I would also like to use my HackRF

@griffinbai tried your suggestion switching to, but still no go. 

I verified the signal again by piping the sound card output directly using GQRX to the input in Win7 PDW using a physical cable, it decoded just fine. any other suggestions? thanks

**Comment by afxmedia** [comment]
can someone post a osx binary that supports FLEX? last thing i would like to try before giving up is to see if there was something wrong with my build. thanks

**Comment by griffinbai** [comment]
@afxmedia 
I don't have HackRF board :octocat: 
BinaryRF is gone I think ,  but I dig some info it might help .
https://goo.gl/rtY860

**Comment by craigshelley** [comment]
It's been a while since I've looked into this,  but I vaguely recall having
a problem with signal polarity and amplitude when I piped from gqrx. I
remember having to apply a negative gain. Use the SCOPE to check the signal
level visually.
-- 
Craig

**Comment by EliasOenal** [comment]
Could you try the samples from the FLEX ticket?
https://github.com/EliasOenal/multimon-ng/issues/1

**Comment by afxmedia** [comment]
@EliasOenal Thanks, tried that and they decoded just fine. Here is a screenshot from PDW when it's doing the decoding, not sure if it's going to help identifying the issue.
![screen shot 2015-12-10 at 9 55 00 am](https://cloud.githubusercontent.com/assets/16061584/11718558/8ce4a264-9f24-11e5-9a5d-9657d4e0cd00.png)

**Comment by afxmedia** [comment]
So I just googled it. The test file from #1 was in 1600/2 mode and it multimon-ng decoded nicely. The one I'm running into trouble from is FLEX 6400/4. Is it not supported?

**Comment by craigshelley** [comment]
Not sure if I've tested 6400. I know it can do /4. The code may require
some tweaking to add 6400 support.
