### ISSUE TITLE
No SCOPE option & 'execlp' dir?

### ISSUE THREAD

**Issue by cpbridges** [EliasOenal/multimon-ng#42]
Just downloaded and built from multimon-ng-1.1.0.zip on Macbook Air / El Capitan.
1. I cannot find the SCOPE option.
2. On startup of the example, I get:

```
Chris-MacBookAir:build chrisbridges$ ./multimon-ng -a DUMPCSV -t wav ../example/x10rf.wav 
multimon-ng  (C) 1996/1997 by Tom Sailer HB9JNX/AE4WA
             (C) 2012-2014 by Elias Oenal
available demodulators: POCSAG512 POCSAG1200 POCSAG2400 FLEX EAS UFSK1200 CLIPFSK FMSFSK AFSK1200 AFSK2400 AFSK2400_2 AFSK2400_3 HAPN4800 FSK9600 DTMF ZVEI1 ZVEI2 ZVEI3 DZVEI PZVEI EEA EIA CCIR MORSE_CW DUMPCSV
Enabled demodulators: DUMPCSV
execlp: No such file or directory
Chris-MacBookAir:build chrisbridges$ 
```

My qmake is:

```
Chris-MacBookAir:build chrisbridges$ qmake -v
QMake version 2.01a
Using Qt version 4.8.6 in /usr/local/Cellar/qt/4.8.6/lib
Chris-MacBookAir:build chrisbridges$ 
```

Any pointers to these two issues?

**Comment by rgrokett** [comment]
You might be missing SOX.  I got the same error on my Raspi with the example x10rf.wav 
$ sudo apt-get install sox

**Comment by EliasOenal** [comment]
> execlp: No such file or directory
This indeed could relate to SoX.

The scope on the other hand is disabled in the qmake file. Check multimon-ng.pro to enable it. (Requires an X server, which isn't available by default on OSX anymore)
