### ISSUE TITLE
Problem building on both Debian 8.3 "Jessie" and Raspbian "Jessie"

### ISSUE THREAD

**Issue by sm4xas** [EliasOenal/multimon-ng#43]
Hello!
I am setting up a MFSK1200 (APRS) reciever using multimon-ng, but I have  a problem. I have installed the "lite" version as I don't need the graphical part.

I can make it work with a RTL-SDR USB stick (with only multimon), but I need to be able to process audio from the mic input, and as I understand it, I then need multimon-ng

These are the steps I am trying:
mkdir ~/src
cd ~/src
git clone https://github.com/EliasOenal/multimonNG.git
cd ~/src/multimonNG
mkdir build
cd build
qmake ../multimon-ng.pro  <--- PROBLEM
make
sudo make install

When I try to runt qmake, I get the following:
qmake: could not find a Qt installation of ''

Do I need QT installed or can I install it any other way? I want to keep this Pi as slim as possible.

Thanks in advance!

**Comment by cpbridges** [comment]
You’ll need qmake for sure. If you want to keep it slim, apt-get install it, use it, then apt-get remove it.

Best, Chris

**Comment by EliasOenal** [comment]
It looks to me like qmake is already installed and complains about the lack of a Qt installation. I never intended Qt to be a build requirement and I am sure building with just qmake and without Qt used to work on Debian in the past.

**Comment by cpbridges** [comment]
Only last week, I used Ubuntu MATE on RPi-2 and didn’t have this problem to build mm-ng. Qt4 may be required but I can’t remember. I doubt Debian is that much different but personally I stick to Ubuntu.

Again, apt-get install/remove will solve this quickly for you ☺ Best, Chris

**Comment by sm4xas** [comment]
I had to install QT as you said, and afterwards it seemed to work.
Thank you!

**Comment by EliasOenal** [comment]
Please post the output of "which qmake" and "ls -la $(which qmake)".
I think it might be a link to qtchooser, in which case you simple have to call the actual qmake binary.

**Comment by sm4xas** [comment]
which qmake: /usr/bin/qmake
ls -la $(which qmake) : lrwxrwxrwx 1 root root 9 Sep 25  2014 /usr/bin/qmake -> qtchooser

How do I do that? (Still quite the beginner in linux)

**Comment by EliasOenal** [comment]
This did the job on the latest Debian for me:
```
$ qmake --version
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
$ alias qmake="/$(find /usr -name qmake | grep qt5)"
$ qmake --version
QMake version 3.0
Using Qt version 5.3.2 in /usr/lib/x86_64-linux-gnu
```
You can adjust "grep qt5" to "grep qt4" if you've installed the qt4 version of qmake. Once you've called the alias line qmake should work as expected. I guess it's a bug in Debian, you might want to report it.

**Comment by GaryWSmith** [comment]
I have the same problem as the OP on a headless installation of Raspbian (Bananian actually). 
The only success above looks like it involved a full QT installation - not just the qmake package. :-(
That is, the solution posted by Elias does not work either. 
What are the steps involved to compile with cmake ??

**Comment by EliasOenal** [comment]
CMake is not supported (by me at least) and I think it has been broken for a while. I'll look into the Debian/Ubuntu qmake issues once I find the time, but strictly speaking this isn't a multimon-ng issue. Those distributions just seem to have broken qmake.
