### ISSUE TITLE
Fails to build on OS X El Capitan (library not found for -lpulse-simple)

### ISSUE THREAD

**Issue by peterg10** [EliasOenal/multimon-ng#49]
I installed `pulseaudio` from mac ports. Created a `build` directory and used `cmake` (couldn't find qmake) but I get this error:

`[100%] Linking C executable multimon-ng
ld: library not found for -lpulse-simple
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [multimon-ng] Error 1
make[1]: *** [CMakeFiles/multimon-ng.dir/all] Error 2
make: *** [all] Error 2`

**Comment by peterg10** [comment]
I found the libraries in `/opt/local/lib/` but they're not referenced in `multimon-ng.pro` which _I think_ is the file `cmake` uses. I added `-L/opt/local/lib` to the `LIB=` line, and uncommented it - still no joy. And there my coding skills run out. I'll look it again later.

**Comment by EliasOenal** [comment]
I don't know about cmake, it's currently unmaintained. Also if you use qmake multimon-ng will build without audio support on OSX. You can get qmake by installing "qt5-mac" from macports.

**Comment by petergspire** [comment]
```
[multimon-ng/build] > install qt5-mac 
--->  Configuring qt5-mac
Error: qt5-mac has been replaced by qt5; please install that instead.
Error: org.macports.configure for port qt5-mac returned: obsolete port
Please see the log file for port qt5-mac for details:
    /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_aqua_qt5-mac/qt5-mac/main.log
To report a bug, follow the instructions in the guide:
    http://guide.macports.org/#project.tickets
Error: Processing of port qt5-mac failed
```

Installed the `qt5`port, still no qmake. I've updated ports to the latest.

**Comment by EliasOenal** [comment]
Please try: `find /opt -name "qmake*"`

**Comment by petergspire** [comment]
Thanks! found it `/opt/local/libexec/qt5/bin/qmake` built and installed successfully now.
