### ISSUE TITLE
Missing capcodes in flex

### ISSUE THREAD

**Issue by linuxpronl** [EliasOenal/multimon-ng#53]
When decoding FLEX I'm missing the CAPCODES...

**Comment by joper112** [comment]
ik ook UNK 00000000000000000000000000

**Comment by Zanoroy** [comment]
@linuxpronl I have fixed the group messaging issues with Multimon-ng you can download the updated demod_flex.c from https://github.com/zanoroy/multimon-ng/ recompile and give it a go
