### ISSUE TITLE
MORSE_CW Output?

### ISSUE THREAD

**Issue by cpbridges** [EliasOenal/multimon-ng#54]
Hi! 

I'm using the following to bring in 48kHz raw data via a fifo from gnuradio but I only see numbers. Any ideas of what I'm doing wrong? The dah is 150 ms, and dits are 50 ms.

> sox -t raw -e floating-point -b32 -r 48k file.raw -esigned-integer -b16 -r 22050 -t raw - | ./multimon-ng -t raw - -a MORSE_CW

19854.376953,21298
19854.421875,17237
19854.468750,13287
19854.513672,9331
19854.558594,5545
19854.603516,1857
19854.648438,-1603
19854.695312,-4875
19854.740234,-7866
19854.785156,-10597
19854.830078,-13007
19854.875000,-15103

73s Chris

**Comment by EliasOenal** [comment]
I think your issue is the "-" after raw. Try the sample on Wikipedia:
`multimon-ng -m -a MORSE_CW -t ogg Wikipedia-Morse.ogg`
