### ISSUE TITLE
file pulse in simple.h mancante

### ISSUE THREAD

**Issue by samu99** [EliasOenal/multimon-ng#61]
manca tutta la libreria di pulse audio nel file simple.h

**Comment by EliasOenal** [comment]
English please!

**Comment by jboone** [comment]
Google Translate leads me to believe that @samu99 has the same issue I did:

> $ make
> 
> gcc -c -m64 -pipe -std=gnu99 -g -O2 -Wall -W -fPIC -DMAX_VERBOSE_LEVEL=3 -DPULSE_AUDIO -DCHARSET_UTF8 -I../../multimon-ng -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o unixinput.o ../unixinput.c
> ../unixinput.c:47:26: fatal error: pulse/simple.h: No such file or directory
>  #include <pulse/simple.h>
>                           ^
> compilation terminated.
> Makefile:384: recipe for target 'unixinput.o' failed
> make: *** [unixinput.o] Error 1

Which was addressed on my Debian/Ubuntu system by "sudo apt install libpulse-dev".
