### ISSUE TITLE
Rtl_fm | sox | multimon

### ISSUE THREAD

**Issue by davidmckenzie** [EliasOenal/multimon-ng#66]
Hey guys,

Not sure if this is best place for it, but seems pretty active lately so figured it was worth a shot. :)

Has anyone had any luck with piping rtl_fm through sox before multimon? When using SDR# -> PDW I've found a bandwidth of 12050hz works perfectly, so was going to try upsampling from that to 22050 for multimon. Tried the following with no luck:

```
rtl_fm -d 0101 -g 100 -E dc -F 0 -l 15 -A lut -f 148.5875M -s12050 - | \
sox -traw -r12050 -es -b16 -c1 -v1 - -traw -es -b16 -c1 -r 22050 - | \
multimon-ng -q -cp -a POCSAG512 -f alpha -t raw /dev/stdin
```

Dropping sox and running at 22050 works, but still not capturing as much data as PDW:

```
rtl_fm -d 0101 -g 100 -E dc -F 0 -l 15 -A lut -f 148.5875M -s22050 - |\
multimon-ng -q -cp -a POCSAG512 -f alpha -t raw /dev/stdin
```

Fwiw, I'm working on a nodejs app that will take and parse the multimon output into a DB and present the data with pretty capcode matching etc. Will be sure to keep you guys in the loop there. :)

Thanks!
Dave

**Comment by Zanoroy** [comment]
I have tested a few feeds, but up-sampling doesn't seem to process very well. I'll have a look at it soon and see if I can help with a solution.

**Comment by jklnz** [comment]
@davidmckenzie strangely I have a lot more success using multimon under windows, I tried to use it with a Raspberry PI but did not have any luck - it would miss half the messages. I can pretty much run it on windows just fine at the same time as PDW as well with no changes. Yeah I do a similar thing at the moment with the messages - they get pushed in to an ASP.NET website which uses regex to decode various message types and display them.

**Comment by davidmckenzie** [comment]
Thanks guys. I ended up getting some pretty good decodes out of it running on my mac. Actually seems to be performing better than SDR# -> PDW running simultaneously now!

Node app is still very much WIP, but got a prototype receiving data here:

https://pagermon-hrng.c9users.io:8080/#/

**Comment by pvachon** [comment]
You might find you'll have more luck using `rtf_fm` to grab a 25kHz chunk of the spectrum then downsample with SoX to 22050 Hz. If you're feeling adventurous, I have a new decoder (`depager`) I've been using w/ similar ARM boards (https://github.com/pvachon/tsl-sdr). I was planning to integrate it back into `multimon-ng` someday, but time is always a problem. :-)

**Comment by davidmckenzie** [comment]
Oooh that looks neat, will have to have a play with it :)

**Comment by jklnz** [comment]
@davidmckenzie wow your site looks much better than mine haha, nice work! Sadly in NZ you are not allowed to publish pager messages like you can in Aus

**Comment by Zanoroy** [comment]
@davidmckenzie, your pagemon looks great. Nice work.

**Comment by davidmckenzie** [comment]
Thanks guys! Will be open sourcing it once it's functionally ready :)

**Comment by joper112** [comment]
@davidmckenzie Can i test your software i like it! maybe you can upload your actual version?

**Comment by davidmckenzie** [comment]
Should have an alpha up on GitHub in about 2-4 weeks. Got a few things to sort out in the server side first, clean up a whole bunch of junk code and make it so that it's not a security nightmare ;)

**Comment by jklnz** [comment]
Hey @davidmckenzie  what is the pic/icon you are using for Fire/Ambo?

**Comment by davidmckenzie** [comment]
@jklnz Uses the fontawesome library: http://fontawesome.io/icons/

Alpha version isn't far off now :) The aliases config page has a picker where you can select from the possible icons.

**Comment by jklnz** [comment]
Oh sweet thanks, I might use those too they look pretty cool.

**Comment by davidmckenzie** [comment]
Uploaded the source - still got a bit to do until I can officially call it 0.1.0, but close enough :)

https://github.com/davidmckenzie/pagermon

I'll close this off now :)
