### ISSUE TITLE
Decoding errors

### ISSUE THREAD

**Issue by ryaneastland** [EliasOenal/multimon-ng#69]
Probably just my not knowing how to set everything up right but I keep ever getting NUL at the end on messages received or Ä instead of [ and Ü instead of ] any ideas.

I'm running on a raspberry pi with rtl_fm input

command
rtl_fm -f 148.9125M -s 22050 | multimon-ng -t raw -a POCSAG512 -f alpha /dev/stdin

**Comment by marshyonline** [comment]
Not just you, I am also getting this.

**Comment by ryaneastland** [comment]
I've worked out it's something to do with the charset that multimon is using so just do a find/replace for the incorrect letters

**Comment by EliasOenal** [comment]
I'm still waiting for someone to implement this, without completely breaking support for the German charset. Please see: https://github.com/EliasOenal/multimon-ng/pull/65

**Comment by pyrog** [comment]
Hi,
Same issue with "french" charset.
[Swissphone pagers](https://www.pwservice.com/pdf_search/de900_de920_programming_manual.pdf) use the following charset:
* FTZ Germany
* US ASCII
* Norway / Danmark
* Switzerland
* Sweden / Finland
* Spain
* France
* Britain
* International
* Italy
* Slovenia


Tested with a **Swissphone DE700** pager set with French charset:
* Input of [rpitx/pocsag](https://github.com/F5OEO/rpitx/tree/master/src/pocsag)
```
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~\x7F
```
* Output of multimode-ng
```
!#$%&'()*+,-./0123456789:; = ?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[Ö]^_`abcdefghijklmnopqrstuvwxyzäöüß
```
* Message displayed on the DE700
```
 !"#$%&'()*+,-./0123456789:;<=>?àABCDEFGHIJKLMNOPQRSTUVWXYZâç§^_`abcdefghijklmnopqrstuvwxyzéùèê¡
```
(DEL character is displayed as an inverted exclamation mark)

Hex | US | FR | DE 
--|--|--|--
40 | @ | à | @

Hex | US | FR | DE 
--|--|--|--
5b | [ | â | Ä
5c | \ | ç | Ö
5d | ] | § | Ü


Hex | US | FR | DE 
--|--|--|--
7b | { | é | ä
7c | ⎜ | ù | ö
7d | } | è | ü
7e | ~ | ê | ß
7F | ␡ | ¡ | ␡

DEL is displayed as `<DEL>` by multimode-ng

**Comment by pyrog** [comment]
According to [NZ Telepermit for pagers](http://www.telepermit.co.nz/PTC251.pdf), the POCSAG charset is [ISO 646](https://en.wikipedia.org/wiki/ISO/IEC_646#Code_page_layout) with **US / IRV (1991)** variant (**ISO-IR-006**).

All other variant are described in the [ISO/IEC_646 Variant comparison chart](https://en.wikipedia.org/wiki/ISO/IEC_646#Variant_comparison_chart).

According to [DecentralizedAmateurPagingNetwork/Core issue #143](https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/143#issuecomment-351952624), AlphaPoc pager used by hams use the **DE** variant (**ISO-IR-021**).

**Comment by pyrog** [comment]
Variant | Code&nbsp;Chart | 24 | 40 | 5B | 5C | 5D | 5E | 5F |60 | 7B | 7C | 7D | 7E
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
US / IRV (1991) | ISO-IR-006 | # | @ | [ | \ | ] | ^ | _ | ` | { | \| | } | ~
DE | ISO-IR-021 | # | **§** | **Ä** | **Ö** | **Ü** | ^ | _ | ` | **ä** | **ö** | **ü** | **ß**
swi (NRCS) | CP01021 | **ù** | **à** | **é** | **ç** | **ê** | **î** | **è** | **ô** | **ä** | **ö** | **ü** | **û**
FR (1983) | ISO-IR-069 | **£** |  **à** | **°** | **ç** | **§** | ^ | _ | **µ** | **é** | **ù** | **è** | **¨**
CA | ISO-IR-121 | # | **à** | **â** | **ç** | **ê** | **î** | _ | **ô** | **é** | **ù** | **è** | **û**
**DE700** | | **$** |  **à** | **â** | **ç** | **§** | ^ | _ | ` | **é** | **ù** | **è** | **ê**
**TPL** | | **$** |  **à** | **°** | **ç** | **§** | ^ | _ | ` | **é** | **ù** | **è** | **‾**

DE700 and TPL pagers with french charset seem to use a mix of FR and CA ISO 646 charset.

**Comment by EliasOenal** [comment]
Thanks for posting that table. Would you be willing to change the default to US and implement a command line flag allowing the selection of the other charsets?

**Comment by pyrog** [comment]
In [pocsag.c#L129](https://github.com/EliasOenal/multimon-ng/blob/master/pocsag.c#L129) we could use a simple `global trtab[128]` and remove the binary search.
So the `--charset` option "just" set the appropriate tab once…

**Comment by EliasOenal** [comment]
Fine with me.

**Comment by shutterfire** [comment]
Same error here but inverted.
German messages with Umlauts. Pager EuroBos Mars displays Ü, multimon_ng outputs '[' (open square bracket)

**Comment by pyrog** [comment]
@shutterfire Do you have a technical manual for this pager with the charset(s) used?

Or could you send this test message with [rpitx](https://github.com/F5OEO/rpitx) ?
```bash
printf "0398900D:Test charset \x24\x40\x5B\x5c\x5d\x5e\x5f\x60\x7b\x7c\x7d\x7e" | sudo ~/src/rpitx/pocsag -f BOS_FREQUENCY -r BOS_BAUD_RATE
```

**Comment by shutterfire** [comment]
Output of the pager:
``Test charset $§ÄÖÜ^_`äöüß``
Output of multimon_ng:
`Test charset $@ÄÖÜ^_`äöüß<NUL><NUL>`
The @ char is wrong, everything else is fine.

**Comment by pyrog** [comment]
I don't add yet charsets for [EuroBos](https://www.eurobos.de/produkte/digitaleMeldeempfaenger), [Swissphone](https://www.swissphone.com/productcategory/pager/) and [TPL](https://tplsystemes.com/categories/3) pagers.

Should we add ?
* a charset option `tpl-DE`, `tpl-FR`, `eurobos-DE`, `eurobos-FR`…
* a config file to specify the "user" charset
* …

TPL seem to use the `FR (1973)` also called `ISO-IR-025`.

**Comment by pyrog** [comment]
Send characters from `0x00` to `0x1f` with the following script:
```bash
printf "1234567A:Test 0x1f (\x1f)" | sudo rpitx/pocsag …
```
(Note: both pagers use the **french charset**).

* Swissphone pager display a `Whitespace character` except for `0x00` and `0x0A` as it end the message.
* TPL pager display the following characters:

Code | Char | Comment
--|--|--
0x00||**end of message**
0x01| |Whitespace character
0x02||**new line**
0x03|£|Pound sign
0x04|¯|Macron
0x05|ë|Latin Small Letter E with diaeresis
0x06|Ü|Latin Capital Letter U with diaeresis
0x07|ê|Latin Small Letter E with circumflex
0x08|î|Latin Small Letter I with circumflex
0x09|â|Latin Small Letter A with circumflex
0x0a||**end of message**
0x0b|ô|Latin Small Letter O with circumflex
0x0c|ï|Latin Small Letter I with diaeresis
0x0d||**new line**
0x0e|°|Degree symbol
0x0f|ç|Latin Small Letter C with cedilla
0x10|§|Section sign
0x11|é|Latin Small Letter E with acute
0x12|ù|Latin Small Letter U with grave
0x13|è|Latin Small Letter E with grave
0x14|¡|Inverted Exclamation Mark
0x15|Ç|Latin Capital letter C with cedilla
0x16|Ñ|Latin Capital letter N with tilde
0x17|¿|Inverted Question Mark
0x18|ñ|Latin Small Letter N with tilde
0x19|Ä|Latin Capital letter A with diaeresis
0x1a|Ö|Latin Capital letter O with diaeresis
0x1b| |Whitespace character
0x1c|ä|Latin Small Letter A with diaeresis
0x1d|ö|Latin Small Letter O with diaeresis
0x1e|ü|Latin Capital Letter U with diaeresis
0x1f|ß|Latin Small Letter sharp S
