### ISSUE TITLE
A lot of Flex invalid Offsets in group messages

### ISSUE THREAD

**Issue by bertinholland** [EliasOenal/multimon-ng#74]
A lot of Flex invalid Offsets in group messages

**SCENARIO:**
`rtl_fm -f 169.65M -M fm -s 22050 -p -1 -g 30 -F 0 > example-rtlfm-5min.out`
`multimon-ng -a FLEX -t raw example-rtlfm-5min.out -v 3 –timestamp`

**PROBLEM:**
11x  “FLEX: Invalid Offsets”  in 5 minute sample file

**CONFIGURATION**:
Raspberry PI 3 Model B
uname –a 
Linux prd 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
RTL_FM dongle is: RTL-SDR brand R820T2 RTL2832U 1PPM TCXO SMA V3 Dongle 
Version multimon_ng V1.1.2 (Latest commit c3d44ce /23-8-2017 EliasOenal)

**EXTRA INFORMATION:**
Rtl_fm ppm is calibrated and stable. Gain is also optimised.
Error is repreducable (10 till 30 procent of the group messages has an invalid offset and is not split up).

**NETWORK:**
Tetra Flex network in Holland for emergency services (FSK 1600/2) 

**EXTRA TEST INFORMATION:**
Test with piping sox buffering (1MB or 10 MB) has the same results.
Test with an higher sample rate (ie rtl_fm 25000) and then downsample it to with sox 22050 rate has the same results.

There are no corrupted or fixed blocks. Synchronisation status is 100%. The Flex signal is 100% and the antenna is near the transmitter (good reception).

**Questions:**
-	Is this a bug in multimon-ng software?
-	Can you reproduce this error?
-	Do you have an advice how to workaround / solution for this problem?

@Zanoroy Can you reply also, I would appreciate. 

Best Regards,
Bert.

**Attached files:**
In flex.zip:
example-rtlfm-5min.out
example-rtlfm-5min-processed.txt
[flex.zip](https://github.com/EliasOenal/multimon-ng/files/1248127/flex.zip)

**Comment by Zanoroy** [comment]
The quick answer is the preable is not being reconised and therefore the message is chipped at the wrong byte. 

Let me run a few tests using your data and see what I find.. 

Modifying the sliding window will probably resolve the issue but it's only a guess at this stage.

I cannot play with this until tomorrow sorry.

**Comment by jklnz** [comment]
Hey @Zanoroy - is there any chance of getting a copy of the C# version of the FLEX decoder you wrote please? Sorry would contact you directly but can't seem to on your github page!

**Comment by bertinholland** [comment]
@Zanoroy 
@jklnz 

**Extra testset 01:**

**Commands generate testset**
rtl_fm -f 169.65M -M fm -s 22050 -p -1 -g 30 -F 0 > example-rtlfm-set01.out
multimon-ng -a FLEX -t raw example-rtlfm-set01.out -v 3 > example-rtlfm-set01.txt

**Attachment**
set01.zip

**Results in file example-rtlfm-set01.txt**
11x invalid offsets message
capgroup code in file [002029568] 10x
capgroup code in file [002029568]  2x

**No Split up group capcodes**
No splitup in example-rtlfm-set01.txt 3 times
Line 22
Line 159
Line 402

**Correct Split Up group capcodes**
9 times

**Total Group messages**
12 times

**Extra information**
0 errors
0 corruptions
0 sync lost

**Questions:**
- Is there a bug in multimon-ng (sometimes not split up group cap)?
- Can I do workround this situation?
- Is there a fix available?
- Do you need more details to reproduce this issue / fix this issue?

Thanks for your investigation, best regards,
Bert from Holland.

[set01.zip](https://github.com/EliasOenal/multimon-ng/files/1254509/set01.zip)

**Comment by bertinholland** [comment]
@Zanoroy 
@jklnz 

**Extra testset 02:**

**Commands generate testset (7 minutes)**
rtl_fm -f 169.65M -M fm -s 22050 -p -1 -g 30 -F 0 > example-rtlfm-set02.out
multimon-ng -a FLEX -t raw example-rtlfm-set01.out -v 3 > example-rtlfm-set02.txt

**Attachment (see below at the end)**
set02.zip

**Results in file example-rtlfm-set02.txt**
capgroup code in file [002029568] 14x
capgroup code in file [002029569]  1x

**No Split up group capcodes**
8x invalid offsets message
No split-up in example-rtlfm-set02.txt 2 times at
Line 136
Line 532

**Correct Split Up group capcodes**
13 times

**Total Group messages**
15 times

**Extra information**
0 errors
0 corruptions
0 sync lost

**Questions:**
- Is there a bug in multimon-ng (sometimes not split up group cap)?
- Is there a workaround available for this issue?
- Is there a fix available?
- Do you need more details to reproduce this issue / fix this issue?

Thanks for your investigation, best regards,
Bert from Holland.

**ATTACHMENT**
[set02.zip](https://github.com/EliasOenal/multimon-ng/files/1254728/set02.zip)

**Comment by Zanoroy** [comment]
@bertinholland I can confirm that the "Issue" is in the demod_flex.c code block.

A code flow issue was the root cause. I was checking for the end of the message block on group messages before splitting the message, therefore incorrectly identified the end block as an Invalid Offset when the messages were split across frames.

I have fixed the code and uploaded to https://github.com/zanoroy/multimon-ng/ you could grab just the [demod_flex.c](https://github.com/Zanoroy/multimon-ng/blob/master/demod_flex.c) and let us know how it goes.

@jklnz: I am happy to share the C# code, but at the moment it is very messy I should clean it up a bit, depending on how badly you want it.

**Comment by bertinholland** [comment]
@Zanoroy 
Thanks for your quick response and fix!
I'm now testing it for 24 hours. Test is in progress.
Test results follow after 24 hours running.

**Comment by jklnz** [comment]
Thanks @Zanoroy - no rush for it, just whenever, was thinking about either making an addin for SDRSharp or a c# app similar to PDW to add in a couple of features that i'd like.

**Comment by bertinholland** [comment]
@Zanoroy 

24 hour Testrun is finished.
Test contains 2454 group messages. All groups were split up correctly.
0 Invalid offsets.
Thanks for this correct fix.
Awesome job!

@Zanoroy Can you start a pull request for the Master branch (EliasOenal/multimon-ng). 
Have a nice day.

Best regards,
Bert from Holland.

**Comment by bertinholland** [comment]
This fix is after 11 days testing 100% good. I will close this issue after the pull request demod_flex.c (https://github.com/zanoroy/multimon-ng/) is successfull implemented in the base release EliasOenal/multimon-ng. Thanks in advance Zanaroy.
