### ISSUE TITLE
Flex Tone Messages

### ISSUE THREAD

**Issue by jklnz** [EliasOenal/multimon-ng#78]
Hey @Zanoroy and @EliasOenal - I was watching multimon-ng running against PDW and I noticed that PDW was showing up messages as "Short Tone" with a numeric body but multimon-ng was not picking these up. I had a look at the source in demod_flex and compared it with PDW and it appears that multimon is treating all tone messages as tone messages whereas PDW correctly checks if it has numeric content.

I had a look at the flex paging spec and it actually calls it "Short Message" rather than tone...

**Comment by jklnz** [comment]
[Japanese Flex Protocol Spec.pdf](https://github.com/EliasOenal/multimon-ng/files/1270555/Japanese.Flex.Protocol.Spec.pdf)

**Comment by jklnz** [comment]
[tone.zip](https://github.com/EliasOenal/multimon-ng/files/1276363/tone.zip)

The relevant info from the log file is:
FLEX: SyncInfoWord: sync_code=0x870c baud=1600 levels=2 polarity=POS zero=-0.016157 envelope=0.223897 symrate=1600.049702
FLEX: State: FIW
FLEX: FrameInfoWord: cycleno=11 frameno=106 fix3=0x3c time=47:18
FLEX: State: SYNC2
FLEX: State: DATA
FLEX: BlockInfoWord: (Phase A) BIW:00000807 AW:01-02 (1 pages)
FLEX: CAPCODE:00000000000b0b34
FLEX: Invalid Offsets

and in PDW it shows up as:
0723764  18:47:01 05-09-17 FLEX-A    StNUM   1600   57074

**Comment by Zanoroy** [comment]
@jkknz Damn, ok let me look into it.

**Comment by Zanoroy** [comment]
Fixed, the length of a message shouldn't be checked for a TONE or Numeric message - it causes the offsets to be detected as invalid. I have uploaded a version of [demod_flex.c](https://github.com/Zanoroy/multimon-ng/blob/master/demod_flex.c) to my github. I will need to raise a pull request once we confirm the fix.


Cheers

**Comment by jklnz** [comment]
NIce work, I'll give it a test and see how it goes 👍

**Comment by jklnz** [comment]
Looking good, it is picking up the same tone messages as PDW so far!

**Comment by bertinholland** [comment]
I can confirm after a testrun of approx 24 hours it is looking good. Zero invalid offsets. Patch is correct and ready to integrate in the base Elias release.

**Comment by Zanoroy** [comment]
Sounds good. I'll raise a pull request once I have access to my pc.

**Comment by jklnz** [comment]
This has been fixed
