### ISSUE TITLE
Bug in flex: When >1 group message in THE SAME frame, no message is displayed for the second group message

### ISSUE THREAD

**Issue by bertinholland** [EliasOenal/multimon-ng#79]
@Zanoroy Can you please have a look at this issue? 
@EliasOenal 

**Case:**
Bug in multimon-ng flex.
When there is more than 1 group message in **_THE SAME_** frame, no message is displayed for the second group message.

**Extra information.**
The case is 100% reproducable and this scenario results in 100% message loss (when there is more than 1 group message in the same frame).

**My configuration and commandline statement:**
Raspberry PI model 3B
rtl_fm -f 169.65M -M fm -s 22050 -p -1 -g 30 -F 0 | multimon-ng -a FLEX -t raw /dev/stdin -v 3 --timestamp >> p2000dump.txt

**Attachment see below**

**Illustration in the attachment of the case**
See Line 517 and 519. 
Line 517: 2017-09-04 14:52:50: FLEX: Found Short Instruction, Group bit: 1 capcodes in group so far 1, adding Capcode: [001420999]
Line 519: 2017-09-04 14:52:50: FLEX: Found Short Instruction, Group bit: 1 capcodes in group so far 2, adding Capcode: [001420059]
There is no output for capcode 1420999 and capcode 1420059, also there is no group capcode output as well [0020295xx].

I found this bug only when there is more than 1 group message  in the same frame.

A few extra examples:
Line 1141 and  1143.

Line 1271 and 1273.

Line 1518 and 1520.

Line 2281 and 2283.

Is there a fix available?
Is there a workaround?

I am available for extra information or for testing a fix.

Thanks for your reply / fix in advance.

[p2000dump.txt](https://github.com/EliasOenal/multimon-ng/files/1275406/p2000dump.txt)

Best regards,
Bert from Holland,

**Comment by Zanoroy** [comment]
Damn, Do you have some raw data I can test with?
We don't use group messaging in Australia so I have nothing to test with.

Happy to supply a fix once I can find the cause.

**Comment by Cholens** [comment]
There may be 1 in between. I have the same problem

[Uploading example-rtlfm.zip…]()

**Comment by Zanoroy** [comment]
Excellent, thanks. I should get a bit of time this morning to have a play.
But I'm flying today so time is limited.

**Comment by Cholens** [comment]
I'll try to get one directly that shows this problem 

Sorry for my bad English

**Comment by Zanoroy** [comment]
Do you know if PDW is able to process these messages?

**Comment by Cholens** [comment]
Yes there it works

**Comment by Cholens** [comment]
As far as I see, decode_phase is only loaded when the script is restarted. Here by losing those data where by those new data picks up

**Comment by Zanoroy** [comment]
Ok, looks like the "Long Address" bit is no getting handled correctly.

I have remove the suspect code and updated my version of the [demod_flex.c](https://github.com/Zanoroy/multimon-ng/blob/master/demod_flex.c)

You can download that version and give it a go..

The error was in the decode_phase within the:
` if (flex->Decode.long_address)
`
Code block.

**Comment by Cholens** [comment]
It works as far as I can see thx :D

**Comment by bertinholland** [comment]
First impression looks good!
Testing is 24 hours in progress. I will report the results. 
Thanks for your fix and quick response. Awesome!

**Comment by bertinholland** [comment]
Tetsrun is completed 24 hours. Result is 100% fix for this case. Good job! 
Can you do a pull request for the master release.?
Thanks, best regards,
Bert from Holland.

**Comment by Zanoroy** [comment]
Excellent

**Comment by bertinholland** [comment]
This fix is after 3 days testing 100% good. I will close this issue after the pull request demod_flex.c (https://github.com/zanoroy/multimon-ng/) is successfull implemented in the base release EliasOenal/multimon-ng. Thanks in advance Zanaroy.
