### ISSUE TITLE
Make Error in file unixinput.c

### ISSUE THREAD

**Issue by DaZeller** [EliasOenal/multimon-ng#80]
got the following error:

`:~/multimon-ng/build$ make
gcc -c -m64 -pipe -std=gnu99 -g -O2 -Wall -W -DMAX_VERBOSE_LEVEL=3 -DPULSE_AUDIO -DCHARSET_UTF8 -I/usr/share/qt4/mkspecs/linux-g++-64 -I../../multimon-ng -I../../multimon-ng -I. -o unixinput.o ../unixinput.c
../unixinput.c:47:26: fatal error: pulse/simple.h: Datei oder Verzeichnis nicht gefunden
 #include <pulse/simple.h>
                          ^
compilation terminated.
Makefile:258: die Regel für Ziel „unixinput.o“ scheiterte
make: *** [unixinput.o] Fehler 1
`

**Comment by jklnz** [comment]
have you installed pulse audio?

**Comment by DaZeller** [comment]
Yes.

`:~$ sudo apt install pulseaudio
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
pulseaudio ist schon die neueste Version (1:10.0-1ubuntu2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
`

**Comment by cintema** [comment]
You probably need the pulseaudio-dev package as well.
