### ISSUE TITLE
FLEX Timeout approx 20 till 30 times a day

### ISSUE THREAD

**Issue by bertinholland** [EliasOenal/multimon-ng#81]
@Zanoroy 

**Case:**
Approx 20 till 30 times a day I will see a timeout in de debug dump (-v 3).
In the same second the message LOCKED appears.

**Example:**
See attachment p2000dump line 622
2017-09-10 21:46:12: FLEX: Timeout
2017-09-10 21:46:12: FLEX: Locked

**Attachment**
See below  radio.raw
See below p2000dump.txt (Line 622)

**Capture command**
 rtl_fm -f 169.65M -M fm -s 22050 -p -1 -g 40 -F 0 | tee radio.raw| multimon-ng -a FLEX -t raw /dev/stdin -v 3 --timestamp > /home/pi/p2000/output/p2000dump.txt

**Configuration**
Raspberry 3 Model B with RTLSDR RTL2832U DVB-T Tuner.
Very good signal, transmitter and receiver nearby
PPM and gain is calibrated and stable.
No errors or corruptions

**Questions**
- Why is the Timeout message displayed 20 till 30 times a day and signal is locked in the same second.
- Is it possible to tune the multimon-ng  software ?
- Or is it possible to tune other (rtl_fm) parameters?

I will appreciate any advice and explaination .

**ATTACHMENTS**
[p2000dump.txt](https://github.com/EliasOenal/multimon-ng/files/1290892/p2000dump.txt)

Radio file, 70 MB  (available 7 days with wetransfer)
https://we.tl/Gj6C2b1KU8 or the same file https://wetransfer.com/downloads/c3e8683bb7ad3ba67e0231952e37774c20170910201018/2be4a1

**Comment by Cholens** [comment]
Try This "rtl_fm -A fast -f 169.65M -M fm -s 22050 -p -1 -g 40 -E dc -F 0 | tee radio.raw| multimon-ng -a FLEX -t raw /dev/stdin -v 3 --timestamp > /home/pi/p2000/output/p2000dump.txt"

**Comment by Zanoroy** [comment]
It's quite normal for the timeouts. I'm attempt an explanation below, if
you need more I can put together an image to help demonstrate what is
happening.

Basically flex sends a preamble to help the reciever get in sink (a lock)
before sending the data packets. While the pager/pc is attempting to lock
the it can see the preamble as having too many crossovers (passing between
positive and negative samples) and adjusts the phase to help "lock" in the
next sample set. In our code if this happens more that 20 times in one
cycle it tells us by reporting a "time out".

The error could say "too many zero crossings lock, adjusting phase".

It's actually what the preamble is there for.

**Comment by bertinholland** [comment]
@Zanoroy Thanks for your explanation. I would appreciate if you publish an image to help demonstrate what is hapening. Thanks in advance.

**Comment by bertinholland** [comment]
@Zanoroy I have a suggestion to change the message "Timeout" to "Adjusting phase - attempt to lock".

**Comment by Zanoroy** [comment]
Yeah, I've be thinking the same. I'm actually away at the moment so I need
to find the time to get online..

**Comment by bertinholland** [comment]
@Cholens thanks for your suggestion to add the option -A fast The results are good and the timeouts disappeared.
