### ISSUE TITLE
FLEX bug group message is not always correct split up (timeout setting is too low)

### ISSUE THREAD

**Issue by bertinholland** [EliasOenal/multimon-ng#87]
**CASE**
Approx 1% of the group messages there is no split-up because there is a timeout in the **_short instruction_** frame. 
@Zanoroy Can you please reply? I would appreciate.

**TESTSCENARIO/EXAMPLE**
[radio.20171008123001-multimondump-WITHbug.txt](https://github.com/EliasOenal/multimon-ng/files/1366887/radio.20171008123001-multimondump-WITHbug.txt)

In cycleno 9 and frameno 115 you can see a timeout. The next frame is a group message and split up does NOT take place.

**EXTRA INFORMATION**
When I see a timeout this has always happened in a short instruction frame.

**TESTSCENARIO (see attached radio file) and I have comment out line 1100** 
See below the files in zip attachment file.
When I comment out line 1100 the split up takes place correctly!
```
		/*Time out after 50 periods with no zero crossing*/
		flex->Demodulator.timeout++;
		if (flex->Demodulator.timeout>50) {
			verbprintf(1, "FLEX: Timeout\n");
			/*flex->Demodulator.locked = 0;*/
		}
```
[radio.20171008123001-multimondump-WITHworkaround.txt](https://github.com/EliasOenal/multimon-ng/files/1366890/radio.20171008123001-multimondump-WITHworkaround.txt)

**SOLUTION SUGGESTION**
Change   if (flex->Demodulator.timeout>50) {
to if (flex->Demodulator.timeout>60) { 

I'm not sure the value 60 is high enough. In the testfile radio.20171008123001-multimondump-WITHworkaround.txt you can see the timeout message is 6 times displays. So the minumum value is 50 + 6. At the moment my test is running to see what is the right timeout value

Note: I think when there are  a lot of short instructions in the frame the value 50 is too low.

**ATTACHED SOURCE FILES IN TIMEOUTBUG.ZIP**
ZIP File contains:
Original file: demod_flexWITHbug.c
Updated file: demod_flexWITHworkaround-commentline1100.c (comment out line 1100)
Testfile: radio.20171008123001.raw

[timeoutbug.zip](https://github.com/EliasOenal/multimon-ng/files/1366888/timeoutbug.zip)

**Comment by bertinholland** [comment]
After 24 hour testing.
Network type 1600/2/A
I investigate that flex->Demodulator.timeout>90 works fine to split up all groups messages.

So I suggest to change the code demod_flex.c
```
	/*Time out after 50 periods with no zero crossing*/
		flex->Demodulator.timeout++;
		if (flex->Demodulator.timeout>50) {
			verbprintf(1, "FLEX: Timeout\n");
			flex->Demodulator.locked = 0;
		}
```
to change to

```
	/*Time out after 90 periods with no zero crossing*/
		flex->Demodulator.timeout++;
		if (flex->Demodulator.timeout>90) {
			verbprintf(1, "FLEX: Timeout\n");
			flex->Demodulator.locked = 0;
		}
```

When the periods with no zero crossing is 90 I receive all groups messages and split-it works fine.

My test scenario is still in progress (for 1 week) with productio radio data to check if the value 90 is high enough.

@Zanoroy What is your opinion about the right timeout value?

**Comment by Zanoroy** [comment]
Honestly, it depends on your receiver + antenna ect.. And I didn't have any
multi messagee flex data to test with.  The higher the value the more
possibility of false lock identification but I haven't seen any running up
to 100 zero crossings.

**Comment by bertinholland** [comment]
@Zanoroy 
I have add an attachment to test  with and it illustrate the issue of not splitting up group messages (10 or 20 times a day approx). Cycle 9 frame 115. This message is not split up (timeout).

[Radiofile-withgroupsplit-issue89.raw.zip](https://github.com/EliasOenal/multimon-ng/files/1367748/Radiofile-withgroupsplit-issue89.raw.zip)

**Comment by bertinholland** [comment]
I have raised the timeout to 100.  The test has run for 7 days and 100% of the short instruction frames is fine. Zero timeouts. And all pager messages are received 100% (I have checked it with pdw). The receiving radio signal is very good. No messages lost. Zero lost synchronisation. Zero invalid offsets.  

- I think when there is a short message frame (group message) the timeout setting 50 is too low and 100 is accurate.
- Is it possible that there is a kind of preamble in the short message frame with higher periods no zero crossings in a short message frame.
- My test shows that timeout 100 is accurate. I think it is a good idea to change this setting in the source in the release. 
- Extra information, when the timeout setting is 50 approx 1% (=20) timeouts per day. 

changed demod_flex.c
```
/*Time out after 50 periods with no zero crossing*/
		flex->Demodulator.timeout++;
		if (flex->Demodulator.timeout>100) {
			verbprintf(1, "FLEX: Timeout\n");
			flex->Demodulator.locked = 0;
		}

```

**Comment by Zanoroy** [comment]
I'll do the same on my end and if the is the same result I'll update my
version and put in a pull request.

**Comment by bertinholland** [comment]
@Zanoroy What are the results of your tests? Are the results good?

**Comment by bertinholland** [comment]
@Zanoroy  Can you please do a pull request with the change you see below. I have changed 50 to 100 and all groupmessages were split up correctly (60 days testrun). Can you please change the code to 100 and do a pull request? Thanks!

/*Time out after 100 periods with no zero crossing*/
		flex->Demodulator.timeout++;
		if (flex->Demodulator.timeout>100) {
			verbprintf(1, "FLEX: Timeout\n");
			flex->Demodulator.locked = 0;
		}

**Comment by joper112** [comment]
Bert kan je mij vertellen wat je veranderd hebt in het verleden, ik zie dat veel nog met 1 capcode wordt gedecodeerd i.p.v. de losse groupmessages

I sakes Bert in dutch hwhat hè change D in history to get iT working

**Comment by Zanoroy** [comment]
I'll need to roll back the latest check in, and then implement your
change.. Before creating the change request.

**Comment by Zanoroy** [comment]
@joper112 : thanks, I think I have captured the changes, but it will be great to get confirmation (Unfortunately, I am a typical Australian and only speak English - Australian English and enough Spanish to order breakfast and coffee 👍)

@bertinholland : I have modified my version, located at: https://github.com/Zanoroy/multimon-ng could you please pull my version and test. 

Background: I had attempted to put another change through to fix another issue that was reported. After testing the I found the  'issue' was not really an 'issue' it was a localisation problem on the users install. I reversed the changes and tested at my end, but it would be nice to confirm.

Once confirmed I will create the pull request.

Cheers

**Comment by joper112** [comment]
@Zanoroy i pulled the latest version from https://github.com/Zanoroy/multimon-ng i start some testing! You guys are so good!

**Comment by bertinholland** [comment]
@Zanoroy Thanks. Testing starting. After a few days running I will report the results.

**Comment by bertinholland** [comment]
@Zanoroy 
Testrun is finished.
Tested objed: demod_flex.c Version 0.8.6v (18 Dec 2017)

Tustrun 104 hours (emmergency service production network Holland Flex/1600/2/A).
All 30147 pages were correctly split up.
0 Invalid offsets
0 Errors
0 Corruptions
0 Lost sync
0 Timouts

Testresult is 100% good.
Code is ready to be integrated in the base release EliasOenal.
Can you please start a pull request.

Thanks for this fix!

**Comment by Zanoroy** [comment]
I'm away on Holidays, when I get back to a pc I'll create the pull request,
thanks for the testing.

**Comment by bertinholland** [comment]
Pull request #92 opened 11 hours ago by Zanoroy  (Various Fixes)
Waiting for integration in base release EliasOenal

**Comment by bertinholland** [comment]
Various Fixes
Pull request #92 by Zanoroy was merged a day ago
is integrated in the EliasOenal master branch.

Test in progress for the master brancg EliasOenal.
After a few days I will report the results. When 100% good I will close this issue 87.

**Comment by bertinholland** [comment]
After 3 days the results are 100% good in the master branch EliasOenal (pull request #92).
@Zanoroy thanks for the implementation of this change.
Issue closed.
