### ISSUE TITLE
Raspberry Pi cmake error

### ISSUE THREAD

**Issue by dmitryelj** [EliasOenal/multimon-ng#90]
Hi,

Thanks for the cool product.

I've got a error when compiling multimon-ng on the Raspberry Pi using cmake:
sudo make install
Error here: make: *** No rule to make target 'install'.  Stop.

**Comment by EliasOenal** [comment]
```
~/projects/multimon-ng/build_cmake $ cmake ..
(...)
$ make
(...)
$ make install
[100%] Built target multimon-ng
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/bin/multimon-ng
```

I can't reproduce the issue on OSX.

**Comment by moorer2k** [comment]
I made an automated installation script for getting RTL-SDR/Multimon-ng/Pagermon working on a fresh dietpi install, it should work fine on other PI distros also.

https://gist.github.com/moorer2k/b29fa54948a19f6e70df30cb8b3fd6cc

Try that.
