### ISSUE TITLE
Truncated pages

### ISSUE THREAD

**Issue by WizRd0** [EliasOenal/multimon-ng#93]
I'm tempted to think this is related to the page being sent and not what i'm able to decode, specifically line 5.

> FLEX: State: DATA
> FLEX: BlockInfoWord: (Phase A) BIW:00000807 AW:01-02 (1 pages)
> FLEX: CAPCODE:00000000001d763f
> FLEX: Parse Alpha Numeric
> FLEX: 2018-01-11 00:40:25 1600/2/A 10.013 [001930815] ALN PA50 PR: 3 - LARGS NORTH 79 Q 11 D00452 Disp: 11:10 Unconsciou
> FLEX: State: SYNC1
> FLEX: SyncInfoWord: sync_code=0x870c baud=1600 levels=2 polarity=POS zero=-0.002133 envelope=0.183335 symrate=1555.772388
> FLEX: State: FIW
> FLEX: FrameInfoWord: cycleno=10 frameno=014 fix3=0x00 time=40:26
> FLEX: State: SYNC2
> FLEX: State: DATA
> FLEX: BlockInfoWord: (Phase A) BIW:00000807 AW:01-02 (1 pages)
> FLEX: CAPCODE:00000000001cfedd
> FLEX: Parse Alpha Numeric
> FLEX: 2018-01-11 00:40:26 1600/2/A 10.014 [001900253] ALN THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  5928
> FLEX: State: SYNC1
> FLEX: SyncInfoWord: sync_code=0x870c baud=1600 levels=2 polarity=POS zero=-0.001780 envelope=0.183305 symrate=1556.178312
> FLEX: State: FIW
> FLEX: FrameInfoWord: cycleno=10 frameno=016 fix3=0x00 time=40:30
> FLEX: State: SYNC2
> FLEX: State: DATA

This seems to be a fairly consistent truncation for Unconscious to Unconsciou, there are several other examples i've seen over the last few weeks.  I'm piping the audio using the command "rtl_fm -f 148.812M -l 48 -s 22.05k | multimon-ng -t raw -a FLEX -f alpha -b 0 -v 4 /dev/stdin".  I've attempted to modify the rtl_fm gain & oversampling, both end up resulting in excessive synchronisation losses or timeouts.

Any thoughts or suggestions on what I could possibly be doing wrong here or is the paging network where I live just meh?

**Comment by rob0101** [comment]
That's how the message was sent.  The sender abbreviates it.

This site shows it as it was sent:  https://www.cfsscan.com/search/Unconsciou
Mine does post-processing to make it more readable:   https://sapaging.com/live?type=Unconsciou

They are standard terms, so easy to map after they have been decoded.

**Comment by Zanoroy** [comment]
That's actually a SACAD issue used within South Australia (SAGRN) and nothing to do with the decoding.

**Comment by Zanoroy** [comment]
@WizRd0 could you please close this issue.
