### ISSUE TITLE
Scope doesn't work in 16.04.4

### ISSUE THREAD

**Issue by hagensieker** [EliasOenal/multimon-ng#98]
I had an Ubuntu box with 16.03 and SCOPE worked just fine.  Did a fresh install of 16.04.4 and SCOPE is just a white box with no signal displayed.  I figured it was me, or something I did, however I installed the latest Skywave Linux, based on Ubuntu 16.04 and SCOPE doesn't work there either.  In the interim I just left out -a SCOPE and to be honest I just minimize it anyway but just wanted to mention that it isn't working at least on the latest buids I have used.   Thanks for multimon-ng.  My friends are blown away that you can read pager traffic from the local hospital.

**Comment by eoineoineoin** [comment]
I noticed the same thing and have submitted pull request #100

**Comment by EliasOenal** [comment]
@eoineoineoin Thanks for the fix!

**Comment by albedo039** [comment]
hello there...sun but cold in paris !!   

about "xdisplay.c" i got the right files without `` while (XNextEvent(display, &evt) == 0) `` sequence (line 115-119 )on two different bionic beaver machines..(ubuntu)
one's got the 1.1.5 multimon-ng , the other 1.1.8...
scope is ok on the 1.1.5 one, not on the other !! (invalid mode "scope")   :( ...
any suggestion master ??
best...
bruno from paris...
